'use client'

import { motion } from 'framer-motion'
import { Globe, Users, Zap, Shield, TrendingUp, Award } from 'lucide-react'
import type { FC } from 'react'

const benefits = [
  {
    icon: Globe,
    title: 'A professional website',
    description: 'That inspires trust and credibility with your potential clients.',
  },
  {
    icon: Users,
    title: 'More visitors converted',
    description: 'Into clients thanks to optimized pages and an effective acquisition strategy.',
  },
  {
    icon: Target,
    title: 'Qualified leads automatically',
    description: 'Generated by forms and optimized conversion funnels.',
  },
  {
    icon: Shield,
    title: 'A credible digital presence',
    description: 'That clearly stands out from your competitors.',
  },
  {
    icon: Zap,
    title: 'A high-performing sales system',
    description: 'That works for you 24/7.',
  },
  {
    icon: TrendingUp,
    title: 'Sustainable growth',
    description: 'Based on data and measurable results.',
  },
]

function Target({ className }: { className: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="12" cy="12" r="5" />
      <circle cx="12" cy="12" r="9" />
    </svg>
  )
}

const BenefitsSection: FC = () => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2,
      },
    },
  }

  const itemVariants = {
    hidden: { opacity: 0, scale: 0.9 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: { duration: 0.6 },
    },
  }

  return (
    <section className="py-12 md:py-20 bg-gradient-to-b from-white to-gray-50 relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute bottom-0 right-0 w-96 h-96 bg-accent-100 rounded-full blur-3xl opacity-30 translate-x-1/3 translate-y-1/3"></div>

      <div className="container-section relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <h2 className="section-title mb-4">
            What your business will{' '}
            <span className="gradient-text">gain</span>
          </h2>
          <p className="text-gray-600 text-lg max-w-2xl mx-auto">
            Concrete and measurable benefits to accelerate your growth.
          </p>
        </motion.div>

        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 md:gap-8"
        >
          {benefits.map((benefit, index) => {
            const Icon = benefit.icon
            return (
              <motion.div
                key={index}
                variants={itemVariants}
                whileHover={{ y: -8 }}
                className="bg-white rounded-2xl p-6 sm:p-8 shadow-md-premium hover:shadow-lg-premium border border-gray-100 transition-all duration-300 relative overflow-hidden group"
              >
                {/* Gradient background on hover */}
                <div className="absolute inset-0 bg-gradient-to-br from-success-50 to-accent-50 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>

                {/* Content */}
                <div className="relative z-10">
                  <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-success-100 to-success-50 flex items-center justify-center mb-4 group-hover:from-success-200 group-hover:to-success-100 transition-colors">
                    <Icon className="w-7 h-7 text-success-600" />
                  </div>

                  <h3 className="text-xl font-bold text-primary-900 mb-3 group-hover:text-success-600 transition-colors">
                    {benefit.title}
                  </h3>
                  <p className="text-gray-600 leading-relaxed group-hover:text-gray-700 transition-colors">
                    {benefit.description}
                  </p>
                </div>
              </motion.div>
            )
          })}
        </motion.div>

        {/* CTA Banner */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          viewport={{ once: true }}
          className="mt-12 bg-white rounded-3xl p-8 md:p-12 shadow-lg-premium border border-gray-100 text-center"
        >
          <h3 className="text-2xl md:text-3xl font-bold mb-4 gradient-text">
            Ready to transform your business?
          </h3>
          <p className="text-gray-600 text-lg mb-8 max-w-2xl mx-auto">
            Start with a free audit to discover how we can help you achieve your goals.
          </p>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="btn btn-primary"
          >
            Request my free audit
          </motion.button>
        </motion.div>
      </div>
    </section>
  )
}

export default BenefitsSection
